# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Countries' do
	pod 'Alamofire', '~> 4.3'
	pod "MagicalRecord"
	pod 'ObjectMapper', '~> 2.2'
	pod 'ReactiveCocoa', '~> 5.0.0'
end
